name: frontend
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  #UI
  cupertino_icons: ^1.0.8

  # functionality
  web_socket_channel: ^3.0.1
  http: ^1.2.2
  shared_preferences: ^2.3.3


  # State management.
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  freezed: ^2.5.7

  # launcher
  icons_launcher: ^3.0.0
  flutter_native_splash: ^2.4.3



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code generation
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true

  assets:
    - assets/
